[<RequireQualifiedAccess>]
module Backend.JokesRepository

    open System

    type JokeRecord = { Text: string }

    let private all = [|
        { Text = "MacGyver can build an airplane out of gum and paper clips. Chuck Norris can kill him and take it." }
        { Text = "Chuck Norris doesn't read books. He stares them down until he gets the information he wants." }
        { Text = "If you ask Chuck Norris what time it is, he always answers \"Two seconds till\". After you ask \"Two seconds to what?\", he roundhouse kicks you in the face." }
        { Text = "Since 1940, the year Chuck Norris was born, roundhouse kick related deaths have increased 13,000 percent." }
        { Text = "Chuck Norris sheds his skin twice a year." }
        { Text = "There are no steroids in baseball. Just players Chuck Norris has breathed on." }
        { Text = "When Chuck Norris goes to donate blood, he declines the syringe, and instead requests a hand gun and a bucket." }
        { Text = "Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after the Chuck gave them a roundhouse kick to the face." }
        { Text = "According to the Encyclopedia Britannica, the Native American \"Trail of Tears\" has been redefined as anywhere that Chuck Norris walks." }
        { Text = "In an average living room there are 1,242 objects Chuck Norris could use to kill you, including the room itself." }
        { Text = "The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn." }
        { Text = "Chuck Norris doesn't shower, he only takes blood baths." }
        { Text = "Time waits for no man. Unless that man is Chuck Norris." }
        { Text = "Chuck Norris can hit you so hard that he can actually alter your DNA. Decades from now your descendants will occasionally clutch their heads and yell \"What The Hell was That?\"." }
        { Text = "In the Bible, Jesus turned water into wine. But then Chuck Norris turned that wine into beer." }
        { Text = "Chuck Norris is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face." }
        { Text = "Faster than a speeding bullet... More powerful than a locomotive... Able to leap tall buildings in a single bound... These are some of Chuck Norris's warm-up exercises." }
        { Text = "Chuck Norris is not hung like a horse. Horses are hung like Chuck Norris." }
        { Text = "Teenage Mutant Ninja Turtles is based on a true story: Chuck Norris once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate." }
        { Text = "Someone once tried to tell Chuck Norris that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made." }
        { Text = "Chuck Norris has two speeds: Walk and Kill." }
        { Text = "Chuck Norris once shot down a German fighter plane with his finger. By yelling \"Bang!\"" }
        { Text = "The opening scene of the movie \"Saving Private Ryan\" is loosely based on games of dodge ball Chuck Norris played in second grade." }
        { Text = "Fool me once, shame on you. Fool Chuck Norris once and he will roundhouse kick you in the face." }
        { Text = "Chuck Norris originally appeared in the \"Street Fighter II\" video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, Norris replied \"That's no glitch.\"" }
        { Text = "If you spell Chuck Norris in Scrabble, you win. Forever." }
        { Text = "Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Massacre." }
        { Text = "Chuck Norris will attain statehood in 2009. His state flower will be the Magnolia." }
        { Text = "A handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there." }
        { Text = "Chuck Norris doesn't wash his clothes. He disembowels them." }
        { Text = "Chuck Norris doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out." }
        { Text = "Police label anyone attacking Chuck Norris as a Code 45-11.... A suicide." }
        { Text = "Chuck Norris is the only man to ever defeat a brick wall in a game of tennis." }
        { Text = "What was going through the minds of all of Chuck Norris' victims before they died? His shoe." }
        { Text = "There is no theory of evolution, just a list of creatures Chuck Norris allows to live." }
        { Text = "Chuck Norris can win a game of Connect Four in only three moves." }
        { Text = "CNN was originally created as the \"Chuck Norris Network\" to update Americans with on-the-spot ass kicking in real-time." }
        { Text = "Chuck Norris invented Kentucky Fried Chicken's famous secret recipe with eleven herbs and spices. Nobody ever mentions the twelfth ingredient: Fear." }
        { Text = "The quickest way to a man's heart is with Chuck Norris' fist." }
        { Text = "When Chuck Norris sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. Chuck Norris has not had to pay taxes, ever." }
        { Text = "Chuck Norris drives an ice cream truck covered in human skulls." }
        { Text = "Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they're all poisonous." }
        { Text = "The Great Wall of China was originally created to keep Chuck Norris out. It failed miserably." }
        { Text = "Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing." }
        { Text = "Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie down." }
        { Text = "Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean." }
        { Text = "When Chuck Norris calls 1-900 numbers, he doesn't get charged. He holds up the phone and money falls out." }
        { Text = "Chuck Norris once ate a whole cake before his friends could tell him there was a stripper in it." }
        { Text = "Some people like to eat frogs' legs. Chuck Norris likes to eat lizard legs. Hence, snakes." }
        { Text = "There are no races, only countries of people Chuck Norris has beaten to different shades of black and blue." }
        { Text = "When Chuck Norris was denied an Egg McMuffin at McDonald's because it was 10:35, he roundhouse kicked the store so hard it became a Wendy's." }
        { Text = "Chuck Norris can't finish a \"color by numbers\" because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red." }
        { Text = "A Chuck Norris-delivered Roundhouse Kick is the preferred method of execution in 16 states." }
        { Text = "When Chuck Norris falls in water, Chuck Norris doesn't get wet. Water gets Chuck Norris." }
        { Text = "Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (Chuck Norris Roundhouse Kick)." }
        { Text = "Chuck Norris' house has no doors, only walls that he walks through." }
        { Text = "How much wood would a woodchuck chuck if a woodchuck could Chuck Norris? All of it." }
        { Text = "Chuck Norris doesn't actually write books, the words assemble themselves out of fear." }
        { Text = "In honor of Chuck Norris, all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be Chuck-sized." }
        { Text = "Chuck Norris can believe it's not butter." }
        { Text = "If tapped, a Chuck Norris roundhouse kick could power the country of Australia for 44 minutes." }
        { Text = "Chuck Norris can divide by zero." }
        { Text = "The grass is always greener on the other side, unless Chuck Norris has been there. In that case the grass is most likely soaked in blood and tears." }
        { Text = "Newton's Third Law is wrong: Although it states that for each action, there is an equal and opposite reaction, there is no force equal in reaction to a Chuck Norris roundhouse kick." }
        { Text = "Chuck Norris invented his own type of karate. It's called Chuck-Will-Kill." }
        { Text = "When an episode of Walker Texas Ranger was aired in France, the French surrendered to Chuck Norris just to be on the safe side." }
        { Text = "While urinating, Chuck Norris is easily capable of welding titanium." }
        { Text = "When Chuck Norris talks, everybody listens. And dies." }
        { Text = "When Steven Seagal kills a ninja, he only takes its hide. When Chuck Norris kills a ninja, he uses every part." }
        { Text = "Wilt Chamberlain claims to have slept with more than 20,000 women in his lifetime. Chuck Norris calls this \"a slow Tuesday.\"" }
        { Text = "Contrary to popular belief, there is indeed enough Chuck Norris to go around." }
        { Text = "Chuck Norris doesnt shave; he kicks himself in the face. The only thing that can cut Chuck Norris is Chuck Norris." }
        { Text = "Chuck Norris always knows the EXACT location of Carmen SanDiego." }
        { Text = "When taking the SAT, write \"Chuck Norris\" for every answer. You will score over 8000." }
        { Text = "Chuck Norris invented black. In fact, he invented the entire spectrum of visible light. Except pink. Tom Cruise invented pink." }
        { Text = "When you're Chuck Norris, anything + anything is equal to 1. One roundhouse kick to the face." }
        { Text = "Chuck Norris has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoly card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO." }
        { Text = "On his birthday, Chuck Norris randomly selects one lucky child to be thrown into the sun." }
        { Text = "Nobody doesn't like Sara Lee. Except Chuck Norris." }
        { Text = "Chuck Norris doesn't throw up if he drinks too much. Chuck Norris throws down!" }
        { Text = "In the beginning there was nothing...then Chuck Norris Roundhouse kicked that nothing in the face and said \"Get a job\". That is the story of the universe." }
        { Text = "Chuck Norris has 12 moons. One of those moons is the Earth." }
        { Text = "Chuck Norris grinds his coffee with his teeth and boils the water with his own rage." }
        { Text = "Archaeologists unearthed an old english dictionary dating back to the year 1236. It defined \"victim\" as \"one who has encountered Chuck Norris\"" }
        { Text = "Chuck Norris ordered a Big Mac at Burger King, and got one." }
        { Text = "Chuck Norris and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building." }
        { Text = "If you Google search \"Chuck Norris getting his ass kicked\" you will generate zero results. It just doesn't happen." }
        { Text = "Chuck Norris can drink an entire gallon of milk in thirty-seven seconds." }
        { Text = "Little known medical fact: Chuck Norris invented the Cesarean section when he roundhouse-kicked his way out of his mother's womb." }
        { Text = "Chuck Norris doesn't bowl strikes, he just knocks down one pin and the other nine faint." }
        { Text = "The show Survivor had the original premise of putting people on an island with Chuck Norris. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage." }
        { Text = "It takes Chuck Norris 20 minutes to watch 60 Minutes." }
        { Text = "You know how they say if you die in your dream then you will die in real life? In actuality, if you dream of death then Chuck Norris will find you and kill you." }
        { Text = "Chuck Norris has a deep and abiding respect for human life... unless it gets in his way." }
        { Text = "The Bermuda Triangle used to be the Bermuda Square, until Chuck Norris Roundhouse kicked one of the corners off." }
        { Text = "Chuck Norris doesn't believe in Germany." }
        { Text = "When Chuck Norris is in a crowded area, he doesn't walk around people. He walks through them." }
        { Text = "Chuck Norris once ate an entire bottle of sleeping pills. They made him blink." }
        { Text = "James Cameron wanted Chuck Norris to play the Terminator. However, upon reflection, he realized that would have turned his movie into a documentary, so he went with Arnold Schwarzenegger." }
        { Text = "Chuck Norris can touch MC Hammer." }
        { Text = "Thousands of years ago Chuck Norris came across a bear. It was so terrified that it fled north into the arctic. It was also so terrified that all of its descendants now have white hair." }
        { Text = "Chuck Norris played Russian Roulette with a fully loaded gun and won." }
        { Text = "It takes 14 puppeteers to make Chuck Norris smile, but only 2 to make him destroy an orphanage." }
        { Text = "Chuck Norris is responsible for China's over-population. He hosted a Karate tournament in Beijing and all women within 1,000 miles became pregnant instantly." }
        { Text = "Some people wear Superman pajamas. Superman wears Chuck Norris pajamas." }
        { Text = "Chuck Norris once worked as a weatherman for the San Diego evening news. Every night he would make the same forecast: Partly cloudy with a 75% chance of Pain." }
        { Text = "Simply by pulling on both ends, Chuck Norris can stretch diamonds back into coal." }
        { Text = "When Chuck Norris does a push-up, he isn't lifting himself up, he's pushing the Earth down." }
        { Text = "Chuck Norris invented the bolt-action rifle, liquor, sexual intercourse, and football-- in that order." }
        { Text = "A high tide means Chuck Norris is flying over your coast. The tide is caused by God pissing his pants." }
        { Text = "Chuck Norris keeps his friends close and his enemies closer. Close enough to drop them with one round house kick to the face." }
        { Text = "There is in fact an 'I' in Norris, but there is no 'team'. Not even close." }
        { Text = "Scotty in Star Trek often says \"Ye cannae change the laws of physics.\" This is untrue. Chuck Norris can change the laws of physics. With his fists." }
        { Text = "An anagram for Walker Texas Ranger is KARATE WRANGLER SEX. I don't know what that is, but it sounds AWESOME." }
        { Text = "Chuck Norris doesn't stub his toes. He accidentally destroys chairs, bed frames, and sidewalks." }
        { Text = "Using his trademark roundhouse kick, Chuck Norris once made a field goal in RJ Stadium in Tampa Bay from the 50 yard line of Qualcomm stadium in San Diego." }
        { Text = "Chuck Norris roundhouse kicks don't really kill people. They wipe out their entire existence from the space-time continuum." }
        { Text = "Chuck Norris does not own a stove, oven, or microwave , because revenge is a dish best served cold." }
        { Text = "Tom Clancy has to pay royalties to Chuck Norris because \"The Sum of All Fears\" is the name of Chuck Norris' autobiography." }
        { Text = "Chuck Norris can slam a revolving door." }
        { Text = "Chuck Norris built a better mousetrap, but the world was too frightened to beat a path to his door." }
        { Text = "The original draft of The Lord of the Rings featured Chuck Norris instead of Frodo Baggins. It was only 5 pages long, as Chuck roundhouse-kicked Sauron's ass halfway through the first chapter." }
        { Text = "Hellen Keller's favorite color is Chuck Norris." }
        { Text = "Chuck Norris eats beef jerky and craps gunpowder. Then, he uses that gunpowder to make a bullet, which he uses to kill a cow and make more beef jerky. Some people refer to this as the \"Circle of Life.\"" }
        { Text = "If, by some incredible space-time paradox, Chuck Norris would ever fight himself, he'd win. Period." }
        { Text = "Chuck Norris is currently suing myspace for taking the name of what he calls everything around you." }
        { Text = "The crossing lights in Chuck Norris's home town say \"Die slowly\" and \"die quickly\". They each have a picture of Chuck Norris punching or kicking a pedestrian." }
        { Text = "Science Fact: Roundhouse kicks are comprised primarily of an element called Chucktanium." }
        { Text = "Chuck Norris proved that we are alone in the universe. We weren't before his first space expedition." }
        { Text = "Superman once watched an episode of Walker, Texas Ranger. He then cried himself to sleep." }
        { Text = "Chuck Norris doesn't step on toes. Chuck Norris steps on necks." }
        { Text = "The movie \"Delta Force\" was extremely hard to make because Chuck had to downplay his abilities. The first few cuts were completely unbelievable." }
        { Text = "Movie trivia: The movie \"Invasion U.S.A.\" is, in fact, a documentary." }
        { Text = "Chuck Norris does not \"style\" his hair. It lays perfectly in place out of sheer terror." }
        { Text = "There is no such thing as global warming. Chuck Norris was cold, so he turned the sun up." }
        { Text = "A study showed the leading causes of death in the United States are: 1. Heart disease, 2. Chuck Norris, 3. Cancer" }
        { Text = "It's widely believed that Jesus was Chuck Norris' stunt double for crucifixion due to the fact that it is impossible for nails to pierce Chuck Norris' skin." }
        { Text = "Chuck Norris did in fact, build Rome in a day." }
        { Text = "Along with his black belt, Chuck Norris often chooses to wear brown shoes. No one has DARED call him on it. Ever." }
        { Text = "Once you go Norris, you are physically unable to go back." }
        { Text = "Ninjas want to grow up to be just like Chuck Norris. But usually they grow up just to be killed by Chuck Norris." }
        { Text = "Chuck Norris once sued Burger King after they refused to put razor wire in his Whopper Jr, insisting that that actually is \"his\" way." }
        { Text = "The last thing you hear before Chuck Norris gives you a roundhouse kick? No one knows because dead men tell no tales." }
        { Text = "Chuck Norris doesn't play god. Playing is for children." }
        { Text = "As a teen, Chuck Norris had sex with every nun in a convent tucked away in the hills of Tuscany. Nine months later the nuns gave birth to the 1972 Miami Dolphins, the only undefeated and untied team in professional football history." }
        { Text = "Chuck Norris is the only person in the world that can actually email a roundhouse kick." }
        { Text = "Chuck Norris won super bowls VII and VIII single-handedly before unexpectedly retiring to pursue a career in ass-kicking." }
        { Text = "Wo hu cang long. The translation from Mandarin Chinese reads: \"Crouching Chuck, Hidden Norris\"" }
        { Text = "Chuck Norris can set ants on fire with a magnifying glass. At night." }
        { Text = "Some kids play Kick the can. Chuck Norris played Kick the keg." }
        { Text = "'Icy-Hot' is too weak for Chuck Norris. After a workout, Chuck Norris rubs his muscles down with liquid-hot MAGMA." }
        { Text = "Chuck Norris cannot love, he can only not kill." }
        { Text = "When Chuck Norris was a baby, he didn't suck his mother's breast. His mother served him whiskey, straight out of the bottle." }
        { Text = "According to Einstein's theory of relativity, Chuck Norris can actually roundhouse kick you yesterday." }
        { Text = "Chuck Norris once pulled out a single hair from his beard and skewered three men through the heart with it." }
        { Text = "In an act of great philanthropy, Chuck made a generous donation to the American Cancer Society. He donated 6,000 dead bodies for scientific research." }
        { Text = "Chuck Norris? favourite cut of meat is the roundhouse." }
        { Text = "When J. Robert Oppenheimer said \"I am become death, the destroyer Of worlds\", He was not referring to the atomic bomb. He was referring to the Chuck Norris halloween costume he was wearing." }
        { Text = "Chuck Norris recently had the idea to sell his urine as a canned beverage. We know this beverage as Red Bull." }
        { Text = "In a recent survey it was discovered the 94% of American women lost their virginity to Chuck Norris. The other 6% were incredibly fat or ugly." }
        { Text = "Chuck Norris invented a language that incorporates karate and roundhouse kicks. So next time Chuck Norris is kicking your ass, don?t be offended or hurt, he may be just trying to tell you he likes your hat." }
        { Text = "If at first you don't succeed, you're not Chuck Norris." }
        { Text = "If Chuck Norris were a calendar, every month would be named Chucktober, and every day he'd kick your ass." }
        { Text = "Fear is not the only emotion Chuck Norris can smell. He can also detect hope, as in \"I hope I don't get a roundhouse kick from Chuck Norris.\"" }
        { Text = "# Chuck Norris's show is called Walker: Texas Ranger, because Chuck Norris doesn't run." }
        { Text = "MacGyver can build an airplane out of gum and paper clips, but Chuck Norris can roundhouse-kick his head through a wall and take it." }
        { Text = "Behind every successful man, there is a woman. Behind every dead man, there is Chuck Norris." }
        { Text = "Chuck Norris brushes his teeth with a mixture of iron shavings, industrial paint remover, and wood-grain alcohol." }
        { Text = "The easiest way to determine Chuck Norris' age is to cut him in half and count the rings." }
        { Text = "There is endless debate about the existence of the human soul. Well it does exist and Chuck Norris finds it delicious." }
        { Text = "Most boots are made for walkin'. Chuck Norris' boots ain't that merciful." }
        { Text = "The US did not boycott the 1980 Summer Olympics in Moscow due to political reasons: Chuck Norris killed the entire US team with a single round-house kick during TaeKwonDo practice." }
        { Text = "Chuck Norris wears a live rattlesnake as a condom." }
        { Text = "The Bible was originally titled \"Chuck Norris and Friends\"" }
        { Text = "Chuck Norris began selling the Total Gym as an ill-fated attempt to make his day-to-day opponents less laughably pathetic." }
        { Text = "Do you know why Baskin Robbins only has 31 flavors? Because Chuck Norris doesn't like Fudge Ripple." }
        { Text = "When Chuck Norris says \"More cowbell\", he MEANS it." }
        { Text = "On the set of Walker Texas Ranger Chuck Norris brought a dying lamb back to life by nuzzling it with his beard. As the onlookers gathered, the lamb sprang to life. Chuck Norris then roundhouse kicked it, killing it instantly. This was just to prove that the good Chuck givet" }
        { Text = "Chuck Norris was what Willis was talkin' about." }
        { Text = "Google won't search for Chuck Norris because it knows you don't find Chuck Norris, he finds you." }
        { Text = "Chuck Norris can lead a horse to water AND make it drink." }
        { Text = "Nagasaki never had a bomb dropped on it. Chuck Norris jumped out of a plane and punched the ground" }
        { Text = "It is scientifically impossible for Chuck Norris to have had a mortal father. The most popular theory is that he went back in time and fathered himself." }
        { Text = "Chuck Norris destroyed the periodic table, because Chuck Norris only recognizes the element of surprise." }
        { Text = "It is believed dinosaurs are extinct due to a giant meteor. That's true if you want to call Chuck Norris a giant meteor." }
        { Text = "Chuck Norris shot the sheriff, but he round house kicked the deputy." }
        { Text = "That's not Chuck Norris doing push-ups -- that's Chuck Norris moving the Earth away from the path of a deadly asteroid." }
        { Text = "Chuck Norris can judge a book by its cover." }
        { Text = "Nothing can escape the gravity of a black hole, except for Chuck Norris. Chuck Norris eats black holes. They taste like chicken." }
        { Text = "Chuck Norris does not play the lottery. It doesn't have nearly enough balls." }
        { Text = "How many Chuck Norris' does it take to change a light bulb? None, Chuck Norris prefers to kill in the dark." }
        { Text = "As President Roosevelt said: \"We have nothing to fear but fear itself. And Chuck Norris.\"" }
        { Text = "Chuck Norris just says \"no\" to drugs. If he said \"yes\", it would collapse Colombia's infrastructure." }
        { Text = "Crime does not pay - unless you are an undertaker following Walker, Texas Ranger, on a routine patrol." }
        { Text = "Chuck Norris invented the internet? just so he had a place to store his porn." }
        { Text = "Chuck Norris does not own a house. He walks into random houses and people move." }
        { Text = "It is better to give than to receive. This is especially true of a Chuck Norris roundhouse kick." }
        { Text = "Chuck Norris is the only person to ever win a staring contest against Ray Charles and Stevie Wonder." }
        { Text = "Industrial logging isn't the cause of deforestation. Chuck Norris needs toothpicks." }
        { Text = "Chuck Norris smells what the Rock is cooking... because the Rock is Chuck Norris' personal chef." }
        { Text = "When Chuck Norris plays Oregon Trail, his family does not die from cholera or dysentery, but rather, roundhouse kicks to the face. He also requires no wagon, since he carries the oxen, axels, and buffalo meat on his back. He always makes it to Oregon before you." }
        { Text = "Chuck Norris is the reason why Waldo is hiding." }
        { Text = "\"Brokeback Mountain\" is not just a movie. It's also what Chuck Norris calls the pile of dead ninjas in his front yard." }
        { Text = "When God said, \"let there be light\", Chuck Norris said, \"say 'please'.\"" }
        { Text = "Chuck Norris does not eat. Food understands that the only safe haven from Chuck Norris' fists is inside his own body." }
        { Text = "Chuck Norris built a time machine and went back in time to stop the JFK assassination. As Oswald shot, Chuck met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement." }
        { Text = "Chuck Norris uses a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris." }
        { Text = "When Bruce Banner gets mad, he turns into the Hulk. When the Hulk gets mad, he turns into Chuck Norris." }
        { Text = "Chuck Norris kills anyone that asks: \"Do you want fries with that?\". Because by now everyone should know that Chuck doesn't want fries with anything. Ever." }
        { Text = "Chuck Norris once kicked a horse in the chin. Its descendants are known today as Giraffes." }
        { Text = "Sticks and stones may break your bones, but a Chuck Norris glare will liquefy your kidneys." }
        { Text = "Human cloning is outlawed because of Chuck Norris, because then it would be possible for a Chuck Norris roundhouse kick to meet another Chuck Norris roundhouse kick. Physicists theorize that this contact would end the universe." }
        { Text = "Chuck Norris once went skydiving, but promised never to do it again. One Grand Canyon is enough." }
        { Text = "Chuck Norris's version of a \"chocolate milkshake\" is a raw porterhouse wrapped around ten Hershey bars, and doused in diesel fuel." }
        { Text = "In a fight between Batman and Darth Vader, the winner would be Chuck Norris." }
        { Text = "Chuck Norris puts his pants on one leg at a time, just like the rest of us. The only difference is, then he kills people." }
        { Text = "Everybody loves Raymond. Except Chuck Norris." }
        { Text = "Contrary to popular belief, the Titanic didn't hit an iceberg. The ship was off course and ran into Chuck Norris while he was doing the backstroke across the Atlantic." }
        { Text = "Chuck Norris got his drivers license at the age of 16. Seconds." }
        { Text = "The original title for Alien vs. Predator was Alien and Predator vs Chuck Norris. The film was cancelled shortly after going into preproduction. No one would pay nine dollars to see a movie fourteen seconds long." }
        { Text = "Chuck Norris? sperm is so badass, he had sex with Nicole Kidman, and 7 months later she prematurely gave birth to a Ford Excursion." }
        { Text = "Chuck Norris can win at solitaire with only 18 cards." }
        { Text = "Chuck Norris once shat blood - the blood of 11,940 natives he had killed and eaten." }
        { Text = "Maslow's theory of higher needs does not apply to Chuck Norris. He only has two needs: killing people and finding people to kill." }
        { Text = "The truth will set you free. Unless Chuck Norris has you, in which case, forget it buddy!" }
        { Text = "Kryptonite has been found to contain trace elements of Chuck Norris roundhouse kicks to the face. This is why it is so deadly to Superman." }
        { Text = "Saddam Hussein was not found hiding in a \"hole.\" Saddam was roundhouse-kicked in the head by Chuck Norris in Kansas, which sent him through the earth, stopping just short of the surface of Iraq." }
        { Text = "Coroners refer to dead people as \"ABC's\". Already Been Chucked." }
        { Text = "Chuck Norris doesn't look both ways before he crosses the street... he just roundhouses any cars that get too close." }
        { Text = "Chuck Norris does not have to answer the phone. His beard picks up the incoming electrical impulses and translates them into audible sound." }
        { Text = "How many roundhouse kicks does it take to get to the center of a tootsie pop? Just one. From Chuck Norris." }
        { Text = "Chuck Norris doesnt wear a watch, HE decides what time it is." }
        { Text = "The phrase 'break a leg' was originally coined by Chuck Norris's co-stars in Walker, Texas Ranger as a good luck charm, indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case." }
        { Text = "When Chuck Norris does division, there are no remainders." }
        { Text = "If you rearrange the letters in \"Chuck Norris\", they also spell \"Crush Rock In\". The words \"with his fists\" are understood." }
        { Text = "Never look a gift Chuck Norris in the mouth, because he will bite your damn eyes off." }
        { Text = "Chuck Norris used to play baseball. When Babe Ruth was hailed as the better player, Chuck Norris killed him with a baseball bat to the throat. Lou Gehrig got off easy." }
        { Text = "The original title for Star Wars was \"Skywalker: Texas Ranger\". Starring Chuck Norris." }
        { Text = "Guantuanamo Bay, Cuba, is the military code-word for \"Chuck Norris' basement\"." }
        { Text = "The phrase 'balls to the wall' was originally conceived to describe Chuck Norris entering any building smaller than an aircraft hangar." }
        { Text = "Chuck Norris? roundhouse kick is so powerful, it can be seen from outer space by the naked eye." }
        { Text = "Ozzy Osbourne bites the heads off of bats. Chuck Norris bites the heads off of Siberian Tigers." }
        { Text = "He who lives by the sword, dies by the sword. He who lives by Chuck Norris, dies by the roundhouse kick." }
        { Text = "The best-laid plans of mice and men often go awry. Even the worst-laid plans of Chuck Norris come off without a hitch." }
        { Text = "The phrase 'dead ringer' refers to someone who sits behind Chuck Norris in a movie theater and forgets to turn their cell phone off." }
        { Text = "Staring at Chuck Norris for extended periods of time without proper eye protection will cause blindess, and possibly foot sized brusies on the face." }
        { Text = "Chuck Norris can taste lies." }
        { Text = "Chuck Norris does not kick ass and take names. In fact, Chuck Norris kicks ass and assigns the corpse a number. It is currently recorded to be in the billions." }
        { Text = "One time, Chuck Norris accidentally stubbed his toe. It destroyed the entire state of Ohio." }
        { Text = "Little Miss Muffet sat on her tuffet, until Chuck Norris roundhouse kicked her into a glacier." }
        { Text = "Chuck Norris can blow bubbles with beef jerky." }
        { Text = "They had to edit the first ending of 'Lone Wolf McQuade' after Chuck Norris kicked David Carradine's ass, then proceeded to barbecue and eat him." }
        { Text = "Chuck Norris does, in fact, live in a round house." }
        { Text = "When Chuck Norris works out on the Total Gym, the Total Gym feels like it's been raped." }
        { Text = "4 out of 5 doctors fail to recommend Chuck Norris as a solution to most problems. Also, 80% of doctors die unexplained, needlessly brutal deaths." }
        { Text = "Chuck Norris can skeletize a cow in two minutes." }
        { Text = "The only sure things are Death and Taxes and when Chuck Norris goes to work for the IRS, they'll be the same thing." }
        { Text = "Chuck Norris' first job was as a paperboy. There were no survivors." }
        { Text = "With the rising cost of gasoline, Chuck Norris is beginning to worry about his drinking habit." }
        { Text = "The square root of Chuck Norris is pain. Do not try to square Chuck Norris, the result is death." }
        { Text = "Chuck Norris' testicles do not produce sperm. They produce tiny white ninjas that recognize only one mission: seek and destroy." }
        { Text = "To be or not to be? That is the question. The answer? Chuck Norris." }
        { Text = "Chuck Norris has never been in a fight, ever. Do you call one roundhouse kick to the face a fight?" }
        { Text = "There are two types of people in the world... people that suck, and Chuck Norris." }
        { Text = "Chuck Norris never wet his bed as a child. The bed wet itself out of fear." }
        { Text = "If you were somehow able to land a punch on Chuck Norris your entire arm would shatter upon impact. This is only in theory, since, come on, who in their right mind would try this?" }
        { Text = "Jean-Claude Van Damme once kicked Chuck Norris' ass. He was then awakened from his dream by a roundhouse kick to the face." }
        { Text = "The pie scene in \"American Pie\" is based on a dare Chuck Norris took when he was younger. However, in Chuck Norris' case, the \"pie\" was the molten crater of an active volcano." }
        { Text = "Chuck Norris uses 8'x10' sheets of plywood as toilet paper." }
        { Text = "Noah was the only man notified before Chuck Norris relieved himself in the Atlantic Ocean." }
        { Text = "MacGyver immediately tried to make a bomb out of some Q-Tips and Gatorade, but Chuck Norris roundhouse-kicked him in the solar plexus. MacGyver promptly threw up his own heart." }
        { Text = "Jack Bauer tried to use his detailed knowledge of torture techniques, but to no avail: Chuck Norris thrives on pain. Chuck Norris then ripped off Jack Bauer's arm and beat him to death with it. Game, set, match." }
        { Text = "Chuck Norris eats steak for every single meal. Most times he forgets to kill the cow." }
        { Text = "The First Law of Thermodynamics states that energy can neither be created nor destroyed... unless it meets Chuck Norris." }
        { Text = "Chuck Norris doesn't go on the internet, he has every internet site stored in his memory. He refreshes webpages by blinking." }
        { Text = "Fact: Chuck Norris doesn't consider it sex if the woman survives." }
        { Text = "It is said that looking into Chuck Norris' eyes will reveal your future. Unfortunately, everybody's future is always the same: death by a roundhouse-kick to the face." }
        { Text = "Chuck Norris knows everything there is to know - Except for the definition of mercy." }
        { Text = "Scientifically speaking, it is impossible to charge Chuck Norris with \"obstruction of justice.\" This is because even Chuck Norris cannot be in two places at the same time." }
        { Text = "Chuck Norris never has to wax his skis because they're always slick with blood." }
        { Text = "When you say \"no one's perfect\", Chuck Norris takes this as a personal insult." }
        { Text = "Chuck Norris can win a game of Trivial Pursuit with one roll of the dice, and without answering a single question... just a nod of the head, and a stroke of the beard." }
        { Text = "182,000 Americans die from Chuck Norris-related accidents every year." }
        { Text = "Paper beats rock, rock beats scissors, and scissors beats paper, but Chuck Norris beats all 3 at the same time." }
        { Text = "Jesus can walk on water, but Chuck Norris can walk on Jesus." }
        { Text = "All roads lead to Chuck Norris. And by the transitive property, a roundhouse kick to the face." }
        { Text = "July 4th is Independence day. And the day Chuck Norris was born. Coincidence? I think not." }
        { Text = "Chuck Norris never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth." }
        { Text = "In the medical community, death is referred to as \"Chuck Norris Disease\"" }
        { Text = "Chuck Norris was once in a knife fight, and the knife lost." }
        { Text = "If you work in an office with Chuck Norris, don't ask him for his three-hole-punch." }
        { Text = "In the Words of Julius Caesar, \"Veni, Vidi, Vici, Chuck Norris\". Translation: I came, I saw, and I was roundhouse-kicked inthe face by Chuck Norris." }
        { Text = "The First rule of Chuck Norris is: you do not talk about Chuck Norris." }
        { Text = "Chuck Norris is widely predicted to be first black president. If you're thinking to yourself, \"But Chuck Norris isn't black\", then you are dead wrong. And stop being a racist." }
        { Text = "When Chuck Norris plays Monopoly, it affects the actual world economy." }
        { Text = "Chuck Norris can be unlocked on the hardest level of Tekken. But only Chuck Norris is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan." }
        { Text = "Chuck Norris drinks napalm to quell his heartburn." }
        { Text = "Every time someone uses the word \"intense\", Chuck Norris always replies \"you know what else is intense?\" followed by a roundhouse kick to the face." }
        { Text = "As an infant, Chuck Norris' parents gave him a toy hammer. He gave the world Stonehenge." }
        { Text = "Chuck Norris once ordered a steak in a restaurant. The steak did what it was told." }
        { Text = "Most people fear the Reaper. Chuck Norris considers him \"a promising Rookie\"." }
        { Text = "There are only two things that can cut diamonds: other diamonds, and Chuck Norris." }
        { Text = "President Roosevelt once rode his horse 100 miles. Chuck Norris carried his the same distance in half the time." }
        { Text = "Chuck Norris once ate four 30lb bowling balls without chewing." }
        { Text = "What many people dont know is Chuck Norris is the founder of planned parenthood. Not even unborn children can escape his wrath." }
        { Text = "Chuck Norris was banned from competitive bullriding after a 1992 exhibition in San Antonio, when he rode the bull 1,346 miles from Texas to Milwaukee Wisconsin to pick up his dry cleaning." }
        { Text = "Chuck Norris qualified with a top speed of 324 mph at the Daytona 500, without a car." }
        { Text = "Chuck Norris likes his coffee half and half: half coffee grounds, half wood-grain alcohol." }
        { Text = "Chuck Norris uses tabasco sauce instead of visine." }
        { Text = "The chemical formula for the highly toxic cyanide ion is CN-. These are also Chuck Norris' initials. This is not a coincidence." }
        { Text = "Chuck Norris' credit cards have no limit. Last weekend, he maxed them out." }
        { Text = "Think of a hot woman. Chuck Norris did her." }
        { Text = "A man once claimed Chuck Norris kicked his ass twice, but it was promptly dismissed as false - no one could survive it the first time." }
        { Text = "Chuck Norris sleeps with a pillow under his gun." }
        { Text = "Chuck Norris owns a chain of fast-food restaurants throughout the southwest. They serve nothing but barbecue-flavored ice cream and Hot Pockets." }
        { Text = "Chuck Norris doesn't chew gum. Chuck Norris chews tin foil." }
        { Text = "Aliens DO indeed exist. They just know better than to visit a planet that Chuck Norris is on." }
        { Text = "When in a bar, you can order a drink called a \"Chuck Norris\". It is also known as a \"Bloody Mary\", if your name happens to be Mary." }
        { Text = "Every time Chuck Norris smiles, someone dies. Unless he smiles while he?s roundhouse kicking someone in the face. Then two people die." }
        { Text = "Some people ask for a Kleenex when they sneeze, Chuck Norris asks for a body bag." }
        { Text = "There?s an order to the universe: space, time, Chuck Norris.... Just kidding, Chuck Norris is first." }
        { Text = "A man once asked Chuck Norris if his real name is \"Charles\". Chuck Norris did not respond, he simply stared at him until he exploded." }
        { Text = "Chuck Norris starts everyday with a protein shake made from Carnation Instant Breakfast, one dozen eggs, pure Colombian cocaine, and rattlesnake venom. He injects it directly into his neck with a syringe." }
        { Text = "In a tagteam match, Chuck Norris was teamed with Hulk Hogan against King Kong Bundy and Andre The Giant. He pinned all 3 at the same time." }
        { Text = "Chuck Norris doesn't see dead people. He makes people dead." }
        { Text = "Chuck Norris is the only person who can simultaneously hold and fire FIVE Uzis: One in each hand, one in each foot -- and the 5th one he roundhouse-kicks into the air, so that it sprays bullets." }
        { Text = "For undercover police work, Chuck Norris pins his badge underneath his shirt, directly into his chest." }
        { Text = "In the X-Men movies, none of the X-Men super-powers are done with special effects. Chuck Norris is the stuntman for every character." }
        { Text = "We live in an expanding universe. All of it is trying to get away from Chuck Norris." }
        { Text = "The word 'Kill' was invented by Chuck Norris. Other words were 'Die', 'Beer', and 'What'." }
        { Text = "The 11th commandment is ?Thou shalt not piss off Chuck Norris? This commandment is rarely enforced, as it is impossible to accomplish." }
        { Text = "Chuck Norris is his own line at the DMV." }
        { Text = "Two wrongs don't make a right. Unless you're Chuck Norris. Then two wrongs make a roundhouse kick to the face." }
        { Text = "Who let the dogs out? Chuck Norris let the dogs out... and then roundhouse kicked them through an Oldsmobile." }
        { Text = "Chuck Norris can do a roundhouse kick faster than the speed of light. This means that if you turn on a light switch, you will be dead before the lightbulb turns on." }
        { Text = "When Chuck Norris goes to out to eat, he orders a whole chicken, but he only eats its soul." }
        { Text = "Chuck Norris has never won an Academy Award for acting... because he's not acting." }
        { Text = "If Chuck Norris wants your opinion, he'll beat it into you." }
        { Text = "Not everyone that Chuck Norris is mad at gets killed. Some get away. They are called astronauts." }
        { Text = "Chuck Norris has to register every part of his body as a separate lethal weapon. His spleen is considered a concealed weapon in over 50 states." }
        { Text = "A movie scene depicting Chuck Norris losing a fight with Bruce Lee was the product of history's most expensive visual effect. When adjusted for inflation, the effect cost more than the Gross National Product of Paraguay." }
        { Text = "Godzilla is a Japanese rendition of Chuck Norris' first visit to Tokyo." }
        { Text = "They once made a Chuck Norris toilet paper, but there was a problem-- It wouldn't take shit from anybody." }
        { Text = "Chuck Norris once rode a nine foot grizzly bear through an automatic car wash, instead of taking a shower." }
        { Text = "\"Sweating bullets\" is literally what happens when Chuck Norris gets too hot." }
        { Text = "Chuck Norris' sperm can be seen with the naked eye. Each one is the size of a quarter." }
        { Text = "After taking a steroids test doctors informed Chuck Norris that he had tested positive. He laughed upon receiving this information, and said \"of course my urine tested positive, what do you think they make steroids from?\"" }
        { Text = "Chuck Norris doesn't daydream. He's too busy giving other people nightmares." }
        { Text = "When Arnold says \"I'll be back\" in Terminator movie it is implied that he's going to ask Chuck Norris for help." }
        { Text = "There are no such things as tornados. Chuck Norris just hates trailer parks." }
        { Text = "Chuck Norris does not follow fashion trends, they follow him. But then he turns around and kicks their ass. Nobody follows Chuck Norris." }
        { Text = "Diamonds are not, despite popular belief, carbon. They are, in fact, Chuck Norris fecal matter. This was proven a recently, when scientific analysis revealed what appeared to be Jean-Claude Van Damme bone fragments inside the Hope Diamond." }
        { Text = "Chuck Norris once participated in the running of the bulls. He walked." }
        { Text = "The Drummer for Def Leppard's only got one arm. Chuck Norris needed a back scratcher." }
        { Text = "Chuck Norris was the orginal sculptor of Mount Rushmore. He completed the entire project using only a bottle opener and a drywall trowel." }
        { Text = "Chuck Norris once rode a bull, and nine months later it had a calf." }
        { Text = "Chuck Norris once lost the remote, but maintained control of the TV by yelling at it in between bites of his \"Filet of Child\" sandwich." }
        { Text = "For Spring Break '05, Chuck Norris drove to Madagascar, riding a chariot pulled by two electric eels." }
        { Text = "The Manhattan Project was not intended to create nuclear weapons, it was meant to recreate the destructive power in a Chuck Norris Roundhouse Kick. They didn't even come close." }
        { Text = "Chuck Norris has banned rainbows from the state of North Dakota." }
        { Text = "Divide Chuck Norris by zero and you will in fact get one........one bad-ass that is." }
        { Text = "TNT was originally developed by Chuck Norris to cure indigestion." }
        { Text = "After returning from World War 2 unscrathed, Bob Dole was congratulated by Chuck Norris with a handshake. The rest is history." }
        { Text = "Chuck Norris runs on batteries. Specifically, Die Hards." }
        { Text = "\"Let the Bodies Hit the Floor\" was originally written as Chuck Norris' theme song." }
        { Text = "Chuck Norris will never have a heart attack. His heart isn't nearly foolish enough to attack him." }
        { Text = "Only Chuck Norris can prevent forest fires." }
        { Text = "When Chuck Norris makes a burrito, its main ingredient is real toes." }
        { Text = "Chuck Norris is not Irish. His hair is soaked in the blood of his victims." }
        { Text = "In the movie \"The Matrix\", Chuck Norris is the Matrix. If you pay close attention in the green \"falling code\" scenes, you can make out the faint texture of his beard." }
        { Text = "They say curiosity killed the cat. This is false. Chuck Norris killed the cat. Every single one of them." }
        { Text = "There is no such thing as a lesbian, just a woman who has never met Chuck Norris." }
        { Text = "Chuck Norris crossed the road. No one has ever dared question his motives." }
        { Text = "When Chuck Norris was born, he immediately had sex with the first nurse he saw. He was her first. She was his third. That afternoon." }
        { Text = "One time, at band camp, Chuck Norris ate a percussionist." }
        { Text = "Chuck Norris doesn't say \"who's your daddy\", because he knows the answer." }
        { Text = "Chuck Norris originally wrote the first dictionary. The definition for each word is as follows - A swift roundhouse kick to the face." }
        { Text = "Love does not hurt. Chuck Norris does." }
        { Text = "The term \"Cleveland Steamer\" got its name from Chuck Norris, when he took a dump while visiting the Rock and Roll Hall of fame and buried northern Ohio under a glacier of fecal matter." }
        { Text = "Chuck Norris once round-house kicked a salesman. Over the phone." }
        { Text = "The pen is mightier than the sword, but only if the pen is held by Chuck Norris." }
        { Text = "Chuck Norris knows the last digit of pi." }
        { Text = "Those aren't credits that roll after Walker Texas Ranger. It is actually a list of fatalities that occurred during the making of the episode." }
        { Text = "The air around Chuck Norris is always a balmy 78 degrees." }
        { Text = "When Chuck Norris wants an egg, he cracks open a chicken." }
        { Text = "Chuck Norris plays racquetball with a waffle iron and a bowling ball." }
        { Text = "According to the Bible, God created the universe in six days. Before that, Chuck Norris created God by snapping his fingers." }
        { Text = "Chuck Norris doesn't believe in ravioli. He stuffs a live turtle with beef and smothers it in pig's blood." }
        { Text = "Count from one to ten. That's how long it would take Chuck Norris to kill you...Forty seven times." }
        { Text = "The 1972 Miami Dolphins lost one game, it was a game vs. Chuck Norris and three seven year old girls. Chuck Norris won with a roundhouse-kick to the face in overtime." }
        { Text = "Chuck Norris is not Politically Correct. He is just Correct. Always." }
        { Text = "Mr. T pities the fool. Chuck Norris rips the fool's head off." }
        { Text = "Chuck Norris had to stop washing his clothes in the ocean. The tsunamis were killing people." }
        { Text = "Chuck Norris has volunteered to remain on earth after the Rapture; he will spend his time fighting the Anti-Christ." }
        { Text = "A man once taunted Chuck Norris with a bag of Lay's potato chips, saying \"Betcha can't eat just one!\" Chuck Norris proceeded to eat the chips, the bag, and the man in one deft move." }
        { Text = "Chuck Norris' favorite cereal is Kellogg's Nails 'N' Gravel." }
        { Text = "In the first Jurassic Park movie, the Tyrannosaurus Rex wasn't chasing the jeep. Chuck Norris was chasing the Tyrannosaurus AND the jeep." }
        { Text = "Chuck Norris has never been accused of murder because his roundhouse kicks are recognized as \"acts of God.\"" }
        { Text = "Chuck Norris does not wear a condom. Because there is no such thing as protection from Chuck Norris." }
        { Text = "Rules of fighting: 1) Don't bring a knife to a gun fight. 2) Don't bring a gun to a Chuck Norris fight." }
        { Text = "Chuck Norris is the only man who has, literally, beaten the odds. With his fists." }
        { Text = "In ancient China there is a legend that one day a child will be born from a dragon, grow to be a man, and vanquish evil from the land. That man is not Chuck Norris, because Chuck Norris killed that man." }
        { Text = "Chuck Norris wipes his ass with chain mail and sandpaper." }
        { Text = "When you play Monopoly with Chuck Norris, you do not pass go, and you do not collect two hundred dollars. You will be lucky if you make it out alive." }
        { Text = "Chuck Norris describes human beings as \"a sociable holder for blood and guts\"." }
        { Text = "Chuck Norris likes his ice like he likes his skulls: crushed." }
        { Text = "Chuck Norris can kick through all 6 degrees of separation, hitting anyone, anywhere, in the face, at any time." }
        { Text = "Most tough men eat nails for breakfast. Chuck Norris does all of his grocery shopping at Home Depot." }
        { Text = "Chuck Norris did not \"lose\" his virginity, he stalked it and then destroyed it with extreme prejudice." }
        { Text = "Everything King Midas touches turnes to gold. Everything Chuck Norris touches turns up dead." }
        { Text = "When Chuck Norris throws exceptions, it's across the room." }
        { Text = "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds." }
        { Text = "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up." }
        { Text = "Chuck Norris writes code that optimizes itself." }
        { Text = "Chuck Norris can't test for equality because he has no equal." }
        { Text = "Chuck Norris doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick()." }
        { Text = "Chuck Norris's first program was kill -9." }
        { Text = "Chuck Norris burst the dot com bubble." }
        { Text = "All browsers support the hex definitions #chuck and #norris for the colors black and blue." }
        { Text = "MySpace actually isn't your space, it's Chuck's (he just lets you use it)." }
        { Text = "Chuck Norris can write infinite recursion functions and have them return." }
        { Text = "Chuck Norris can solve the Towers of Hanoi in one move." }
        { Text = "The only pattern Chuck Norris knows is God Object." }
        { Text = "Chuck Norris finished World of Warcraft." }
        { Text = "Project managers never ask Chuck Norris for estimations... ever." }
        { Text = "Chuck Norris doesn't use web standards as the web will conform to him." }
        { Text = "\"It works on my machine\" always holds true for Chuck Norris." }
        { Text = "Whiteboards are white because Chuck Norris scared them that way." }
        { Text = "Chuck Norris doesn't do Burn Down charts, he does Smack Down charts." }
        { Text = "Chuck Norris can delete the Recycling Bin." }
        { Text = "Chuck Norris's beard can type 140 wpm." }
        { Text = "Chuck Norris can unit test entire applications with a single assert." }
        { Text = "Chuck Norris doesn't bug hunt as that signifies a probability of failure, he goes bug killing." }
        { Text = "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris." }
        { Text = "When Chuck Norris is web surfing websites get the message \"Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?\"." }
        { Text = "Chuck Norris can overflow your stack just by looking at it." }
        { Text = "To Chuck Norris, everything contains a vulnerability." }
        { Text = "Chuck Norris doesn't need sudo, he just types \"Chuck Norris\" before his commands." }
        { Text = "Chuck Norris doesn't need a debugger, he just stares down the bug until the code confesses." }
        { Text = "Chuck Norris can access private methods." }
        { Text = "Chuck Norris can instantiate an abstract class." }
        { Text = "Chuck Norris does not need to know about class factory pattern. He can instantiate interfaces." }
        { Text = "The class object inherits from Chuck Norris" }
        { Text = "For Chuck Norris, NP-Hard = O(1)." }
        { Text = "Bill Gates thinks he's Chuck Norris. Chuck Norris actually laughed. Once." }
        { Text = "Chuck Norris is actually the front man for Apple. He let's Steve Jobs run the show when he's on a mission. Chuck Norris is always on a mission." }
        { Text = "Chuck Norris' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him." }
        { Text = "Chuck Norris solved the Travelling Salesman problem in O(1) time. Here's the pseudo-code: Break salesman into N pieces. Kick each piece to a different city." }
        { Text = "No statement can catch the ChuckNorrisException." }
        { Text = "Chuck Norris doesn't pair program." }
        { Text = "Chuck Norris can write multi-threaded applications with a single thread." }
        { Text = "Chuck Norris doesn't need to use AJAX because pages are too afraid to postback anyways." }
        { Text = "Chuck Norris doesn't use reflection, reflection asks politely for his help." }
        { Text = "There is no Esc key on Chuck Norris' keyboard, because no one escapes Chuck Norris." }
        { Text = "Chuck Norris can binary search unsorted data." }
        { Text = "Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds." }
        { Text = "Chuck Norris doesn't needs try-catch, exceptions are too afraid to raise." }
        { Text = "Chuck Norris went out of an infinite loop." }
        { Text = "If Chuck Norris writes code with bugs, the bugs fix themselves." }
        { Text = "Chuck Norris hosting is 101% uptime guaranteed." }
        { Text = "Chuck Norris's keyboard has the Any key." }
        { Text = "Chuck Norris can access the DB from the UI." }
        { Text = "Chuck Norris' programs never exit, they terminate." }
        { Text = "Chuck Norris insists on strongly-typed programming languages." }
        { Text = "Chuck Norris protocol design method has no status, requests or responses, only commands." }
        { Text = "Chuck Norris programs occupy 150% of CPU, even when they are not executing." }
        { Text = "Chuck Norris can spawn threads that complete before they are started." }
        { Text = "Chuck Norris programs do not accept input." }
        { Text = "Chuck Norris can install iTunes without installing Quicktime." }
        { Text = "Chuck Norris doesn't need an OS." }
        { Text = "Chuck Norris's OSI network model has only one layer - Physical." }
        { Text = "Chuck Norris can compile syntax errors." }
        { Text = "Every SQL statement that Chuck Norris codes has an implicit \"COMMIT\" in its end." }
        { Text = "Chuck Norris does not need to type-cast. The Chuck-Norris Compiler (CNC) sees through things. All way down. Always." }
        { Text = "Chuck Norris does not code in cycles, he codes in strikes." }
        { Text = "Chuck Norris doesn't use a computer because a computer does everything slower than Chuck Norris." }
        { Text = "Chuck Norris compresses his files by doing a flying round house kick to the hard drive." }
        { Text = "Chuck Norris solved the halting problem." }
        { Text = "Chuck Norris doesn't cheat death. He wins fair and square." }
        { Text = "Chuck Norris once won a game of connect four in 3 moves." }
        { Text = "With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions." }
        { Text = "Chuck Norris can do a wheelie on a unicycle." }
        { Text = "Chuck Norris can win in a game of Russian roulette with a fully loaded gun." }
        { Text = "Chuck Norris eats lightning and shits out thunder." }
        { Text = "Chuck Norris can retrieve anything from /dev/null." }
        { Text = "No one has ever pair-programmed with Chuck Norris and lived to tell about it." }
        { Text = "No one has ever spoken during review of Chuck Norris' code and lived to tell about it." }
        { Text = "Chuck Norris doesn't use GUI, he prefers COMMAND line." }
        { Text = "Chuck Norris doesn't use Oracle, he is the Oracle." }
        { Text = "Chuck Norris can dereference NULL." }
        { Text = "Jesus can walk on water, but Chuck Norris can swim through land." }
        { Text = "A diff between your code and Chuck Norris's is infinite." }
        { Text = "The Chuck Norris Eclipse plugin made alien contact." }
        { Text = "Chuck Norris is the ultimate mutex, all threads fear him." }
        { Text = "Chuck Norris uses canvas in IE." }
        { Text = "Don't worry about tests, Chuck Norris's test cases cover your code too." }
        { Text = "Each hair in Chuck Norris's beard contributes to make the world's largest DDOS." }
        { Text = "Chuck Norris's log statements are always at the FATAL level." }
        { Text = "Chuck Norris's database has only one table, 'Kick', which he DROPs frequently." }
        { Text = "When Chuck Norris break the build, you can't fix it, because there is not a single line of code left." }
        { Text = "Chuck Norris types with one finger. He points it at the keyboard and the keyboard does the rest." }
        { Text = "Chuck Norris's programs can pass the Turing Test by staring at the interrogator." }
        { Text = "If you try to kill -9 Chuck Norris's programs, it backfires." }
        { Text = "Chuck Norris's brain waves are suspected to be harmful to cell phones." }
        { Text = "Chuck Norris does infinite loops in 4 seconds." }
        { Text = "Product Owners never ask Chuck Norris for more features. They ask for mercy." }
        { Text = "Product Owners never argue with Chuck Norris after he demonstrates the DropKick feature." }
        { Text = "Chuck Norris killed two stones with one bird." }
        { Text = "Chuck Norris can speak Braille." }
        { Text = "Chuck Norris can over-write a locked variable." }
        { Text = "Chuck Norris knows the value of NULL, and he can sort by it too." }
        { Text = "Chuck Norris can install a 64 bit OS on 32 bit machines." }
        { Text = "Chuck Norris can write to an output stream." }
        { Text = "Chuck Norris can read from an input stream." }
        { Text = "Chuck Norris never has to build his program to machine code. Machines have learnt to interpret Chuck Norris code." }
        { Text = "Chuck Norris' unit tests don't run. They die." }
        { Text = "Chuck Norris sits at the stand-up." }
        { Text = "Chuck Norris doesn't need an account. He just logs in." }
        { Text = "How many Chuck Norris require to screw a light bulb? None, he will screw it all." }
        { Text = "Chuck Norris causes the Windows Blue Screen of Death." }
        { Text = "Chuck Norris can download emails with his pick-up." }
        { Text = "Chuck Norris can make a class that is both abstract and final." }
        { Text = "Chuck Norris could use anything in java.util.* to kill you, including the javadocs." }
        { Text = "Code runs faster when Chuck Norris watches it." }
        { Text = "Only Chuck Norris shuts down websites without due process, not SOPA or PIPA." }
        { Text = "Chuck Norris does not need a watch, he decides what time it is." }
        { Text = "Chuck Norris already went to Moon and Mars, that's why there are no signs of life." }
        { Text = "Once a police officer caught Chuck Norris, the cop was lucky enough to escape with a warning." }
        { Text = "Chuck Norris knows Victoria's secret." }
        { Text = "Dark spots on the Moon are the result of Chuck Norris' shooting practice." }
        { Text = "Chuck Norris died before 20 years, Death doesn't have the courage to tell him yet." }
        { Text = "There is no April 1st in Chuck Norris' calendar, because no one can fool him." }
        { Text = "Chuck Norris can make onions cry." }
        { Text = "Chuck Norris can watch the radio." }
        { Text = "Chuck Norris built the hospital he was born in." }
        { Text = "Once Chuck Norris signed a cheque and the bank bounced." }
        { Text = "Chuck Norris can drown a fish." }
        { Text = "Once death had a near Chuck Norris experience." }
        { Text = "Once Chuck Norris and Superman had a competition. The loser had to wear his underwear over his pants." }
        { Text = "Chuck Norris can make fire using two ice cubes." }
        { Text = "Chuck Norris tears can cure the cancer, but the sad thing is Chuck Norris never cries." }
        { Text = "Chuck Norris can remember the future." }
        { Text = "Chuck Norris doesn't age, because time cannot keep up with him." }
        { Text = "Ghosts are actually caused by Chuck Norris killing people faster than Death can process them." }
        { Text = "Chuck Norris understands every definition in the Oxford Thesaurus, except one - \"mercy\"." }
        { Text = "Chuck Norris doesn't need a keyboard he tells the computer to write something and it does." }
        { Text = "Chuck Norris once pissed in a gas tank of a semi truck as a joke - that truck is now know as Optimus Prime." }
        { Text = "Chuck Norris plays pool with comets and asteroids. He shoots them into black holes." }
        { Text = "There was never anything wrong with Achilles' heel until he got mad and decided to kick Chuck Norris." }
        { Text = "Did you know that Chuck Norris was in every Star Wars movie? He was \"The Force\"." }
        { Text = "Knock knock, who's there? Chuck Norris! Chuck Norris who? Sorry, joke is over when Chuck Norris gets involved!" }
        { Text = "Chuck Norris doesn't win, he allows you to lose." }
        { Text = "Tornadoes occur when Chuck Norris sneezes." }
        { Text = "Chuck Norris once sold eBay to eBay on eBay." }
        { Text = "Chuck Norris can build a snowman out of rain." }
        { Text = "Chuck Norris made the sun by rubbing his hands together." }
        { Text = "Chuck Norris doesn't turn on his faucet, he stares at it until it cries." }
        { Text = "Chuck Norris puts sunglasses on to protect the sun from his eyes." }
        { Text = "Chuck Norris can lock a safe and keep the key inside it." }
    |]

    let private generator = Random()

    let random _ =
        let randomIndex = generator.Next(0, Array.length all - 1)
        Array.get all randomIndex
